name: ubuntu-weather-app
version: '0.1'
summary: ubuntu weather app.
description: |
    A weather forecast application for Ubuntu with support for multiple online weather data sources.
grade: devel
confinement: strict
architectures: [all]

apps:
    ubuntu-weather-app:
        aliases: [ubuntu-weather-app]
        command: desktop-launch qmlscene $SNAP/usr/share/ubuntu-weather-app/app/ubuntu-weather-app.qml 
        plugs:
            - network
            - location-observe
            - opengl
            - platform
            - unity7
            - unity8
            - mir-libs

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target:  ubuntu-app-platform
        default-provider: ubuntu-app-platform
    mir-libs:
        interface: content
        content: mir0 
        target: mir-libs
        default-provider: mir-libs

parts:
    ubuntu-weather-app:
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
        source: .
        build-packages:
            - cmake
            - intltool
        after: [desktop-ubuntu-app-platform]

    environment:
        source: snap/
        plugin: dump
